export const ERROR_CODES = {
  ARTICLE_NOT_FOUND: "ARTICLE_NOT_FOUND",
  ARTICLE_SLUG_NOT_FOUND: "ARTICLE_SLUG_NOT_FOUND",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_INACTIVE: "CATEGORY_INACTIVE",
  CATEGORY_SLUG_EXISTS: "CATEGORY_SLUG_EXISTS",
  INVALID_ARTICLE_STATUS: "INVALID_ARTICLE_STATUS",
  INVALID_PUBLISH_DATE: "INVALID_PUBLISH_DATE",
  ARTICLE_ALREADY_ARCHIVED: "ARTICLE_ALREADY_ARCHIVED",
  IMAGE_TYPE_NOT_SUPPORTED: "IMAGE_TYPE_NOT_SUPPORTED",
  IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOTE_NOT_FOUND: "NOTE_NOT_FOUND",
  NOTE_CONTENT_REQUIRED: "NOTE_CONTENT_REQUIRED",
  INVALID_NOTE_COLOR: "INVALID_NOTE_COLOR",
  NOTE_ACCESS_DENIED: "NOTE_ACCESS_DENIED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
